// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YukonTest.Domain;

namespace YukonTest.Domain.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("YukonTest.Models.Absent", b =>
                {
                    b.Property<int>("AbsentID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AbsentDay");

                    b.Property<int>("TeacherID");

                    b.HasKey("AbsentID");

                    b.ToTable("Absents");
                });

            modelBuilder.Entity("YukonTest.Models.Day", b =>
                {
                    b.Property<int>("DayID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DayName");

                    b.HasKey("DayID");

                    b.ToTable("Days");
                });

            modelBuilder.Entity("YukonTest.Models.Period", b =>
                {
                    b.Property<int>("PeriodID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("PeriodName");

                    b.HasKey("PeriodID");

                    b.ToTable("Periods");
                });

            modelBuilder.Entity("YukonTest.Models.PeriodByDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DayID");

                    b.Property<int>("PeriodID");

                    b.Property<int>("SubjectID");

                    b.Property<int>("TeacherID");

                    b.HasKey("Id");

                    b.ToTable("PeriodByDays");
                });

            modelBuilder.Entity("YukonTest.Models.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("SubjectName");

                    b.HasKey("SubjectId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("YukonTest.Models.Teacher", b =>
                {
                    b.Property<int>("TeacherID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Leave");

                    b.Property<string>("Name");

                    b.Property<int>("SubjectID");

                    b.HasKey("TeacherID");

                    b.ToTable("Teachers");
                });
#pragma warning restore 612, 618
        }
    }
}
